spring.datasource.url=jdbc:postgresql://localhost:5432/tf_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.expiracao=1
security.jwt.chave-assinatura=tf9k2m8x4qw7n3z6vb1jhg5dprc0sl8yueoiakfm2wxqzbn7vtj3hg9mnop12345
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG