spring.datasource.url=jdbc:postgresql://localhost:5432/teamsflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.expiracao=1
security.jwt.chave-assinatura=teamsflow-chave-secreta-super-segura-2026-jwt-512bits-ok
