spring.application.name=teamsFlow
# Altere "nomedoseubanco" para o nome do banco que você criou no Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/tmsflw
spring.datasource.username=postgres
# Insira a senha do seu usuário do Postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 2. CONFIGURAÇÕES DO SPRING DATA JPA / HIBERNATE
# ==========================================
# O Dialeto ajuda o Hibernate a gerar o SQL otimizado para o PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto: 'update' atualiza o banco de dados conforme você muda suas Entidades.
# Outras opções: 'create' (apaga e recria toda vez) ou 'validate' (apenas verifica, ideal para produção).
spring.jpa.hibernate.ddl-auto=update

# Exibir as consultas SQL no console (ótimo para debugar e ver o que o JPA está fazendo)
spring.jpa.show-sql=true

# Formatar o SQL no console para ficar mais legível
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# 3. CONFIGURAÇÕES DO SERVIDOR WEB
# ==========================================
# Porta onde a sua API vai rodar (o padrão é 8080)
server.port=8080

# ==========================================
# 4. CONFIGURAÇÕES DO SPRING BOOT DEVTOOLS
# ==========================================
# Habilita o reinício rápido automático quando você salva o código
spring.devtools.restart.enabled=true